<?php
//
// File generated by Dolibarr installer 19.0.1 on May 03, 2024
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//

$dolibarr_main_url_root='https://vagainc.ca/dbvaga19';
//$dolibarr_main_document_root='/home2/vagainc/public_html/dbvaga19';
$dolibarr_main_document_root=realpath(__DIR__.'/..');
$dolibarr_main_url_root_alt='/home2/vagainc/public_html/dbvaga19/custom';
$dolibarr_main_document_root_alt='/home2/vagainc/dbvaga19/custom';
//$dolibarr_main_data_root='/home2/vagainc/dolibarrdata';
$dolibarr_main_data_root='/home2/vagainc/public_html/dbvaga19/documents';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='3306';
$dolibarr_main_db_name='vagainc_dbvaga19';
$dolibarr_main_db_prefix='vg_';
$dolibarr_main_db_user='vagainc_erpuser';
$dolibarr_main_db_pass='Welcome@123^^^';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mariadb-dump, mariadb, mysqldump, mysql, pg_dump, pgrestore, clamdscan, clamscan.exe';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='023e91e8486e7ebad986681d5a74d896';
$dolibarr_mailing_limit_sendbyweb='0';
$dolibarr_mailing_limit_sendbycli='0';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
$dolibarr_main_distrib='standard';
